name: fpl-backend

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/fpl_db
      REDIS_URL: redis://redis:6379/0
      DB_HOST: db

    volumes:
      - .:/code

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fpl_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:

