apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpl-backend-dep
spec:
  selector:
    matchLabels:
      app: fpl-backend
  replicas: 3

  template:
    metadata:
      labels:
        app: fpl-backend

    spec:
      containers:
        - name: fpl-backend-container
          image: fpl-backend-web:latest
          imagePullPolicy: ifNotPresent
          ports:
            containerPort: 8000