"""Added hash attribute

Revision ID: 50af96824020
Revises: 6b2c08f45722
Create Date: 2024-08-19 13:26:15.011612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50af96824020'
down_revision: Union[str, None] = '6b2c08f45722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('hash_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'hash_value')
    # ### end Alembic commands ###
