"""Updated detail table

Revision ID: 7d25bd91c167
Revises: e94ed8577659
Create Date: 2024-08-08 12:23:04.216601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d25bd91c167'
down_revision: Union[str, None] = 'e94ed8577659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_detail', sa.Column('minutes', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('goals_scored', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('clean_sheet', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('goals_conceded', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('own_goals', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('penalties_saved', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('penalties_missed', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('yellow_cards', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('red_cards', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('bonus', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('bps', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('influence', sa.Float(), nullable=True))
    op.add_column('players_detail', sa.Column('creativity', sa.Float(), nullable=True))
    op.add_column('players_detail', sa.Column('threat', sa.Float(), nullable=True))
    op.add_column('players_detail', sa.Column('ict_index', sa.Float(), nullable=True))
    op.add_column('players_detail', sa.Column('value', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('selected', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('transfers_in', sa.Integer(), nullable=True))
    op.add_column('players_detail', sa.Column('transfers_out', sa.Integer(), nullable=True))
    op.drop_column('players_detail', 'goals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_detail', sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('players_detail', 'transfers_out')
    op.drop_column('players_detail', 'transfers_in')
    op.drop_column('players_detail', 'selected')
    op.drop_column('players_detail', 'value')
    op.drop_column('players_detail', 'ict_index')
    op.drop_column('players_detail', 'threat')
    op.drop_column('players_detail', 'creativity')
    op.drop_column('players_detail', 'influence')
    op.drop_column('players_detail', 'bps')
    op.drop_column('players_detail', 'bonus')
    op.drop_column('players_detail', 'saves')
    op.drop_column('players_detail', 'red_cards')
    op.drop_column('players_detail', 'yellow_cards')
    op.drop_column('players_detail', 'penalties_missed')
    op.drop_column('players_detail', 'penalties_saved')
    op.drop_column('players_detail', 'own_goals')
    op.drop_column('players_detail', 'goals_conceded')
    op.drop_column('players_detail', 'clean_sheet')
    op.drop_column('players_detail', 'goals_scored')
    op.drop_column('players_detail', 'minutes')
    # ### end Alembic commands ###
