"""Add players attributes

Revision ID: e94ed8577659
Revises: 5b4fa659240f
Create Date: 2024-07-29 10:29:06.325997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94ed8577659'
down_revision: Union[str, None] = '5b4fa659240f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('form', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('selected_by_percent', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('total_points', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('minutes', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('goals_scored', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('assists', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('clean_sheets', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('goals_conceded', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('own_goals', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('penalties_saved', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('penalties_missed', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('yellow_cards', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('red_cards', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('bonus', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('bps', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('influence', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('creativity', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('threat', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('ict_index', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('starts', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('expected_goals', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('expected_assists', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('expected_goals_conceded', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('expected_goals_involvement', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('expected_goals_per_90', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('saves_per_90', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('expected_assists_per_90', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('expected_goals_involvements_per_90', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('expected_goals_conceded_per_90', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('goals_conceded_per_90', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('points_per_game', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'points_per_game')
    op.drop_column('players', 'goals_conceded_per_90')
    op.drop_column('players', 'expected_goals_conceded_per_90')
    op.drop_column('players', 'expected_goals_involvements_per_90')
    op.drop_column('players', 'expected_assists_per_90')
    op.drop_column('players', 'saves_per_90')
    op.drop_column('players', 'expected_goals_per_90')
    op.drop_column('players', 'expected_goals_involvement')
    op.drop_column('players', 'expected_goals_conceded')
    op.drop_column('players', 'expected_assists')
    op.drop_column('players', 'expected_goals')
    op.drop_column('players', 'starts')
    op.drop_column('players', 'ict_index')
    op.drop_column('players', 'threat')
    op.drop_column('players', 'creativity')
    op.drop_column('players', 'influence')
    op.drop_column('players', 'bps')
    op.drop_column('players', 'bonus')
    op.drop_column('players', 'saves')
    op.drop_column('players', 'red_cards')
    op.drop_column('players', 'yellow_cards')
    op.drop_column('players', 'penalties_missed')
    op.drop_column('players', 'penalties_saved')
    op.drop_column('players', 'own_goals')
    op.drop_column('players', 'goals_conceded')
    op.drop_column('players', 'clean_sheets')
    op.drop_column('players', 'assists')
    op.drop_column('players', 'goals_scored')
    op.drop_column('players', 'minutes')
    op.drop_column('players', 'total_points')
    op.drop_column('players', 'selected_by_percent')
    op.drop_column('players', 'form')
    # ### end Alembic commands ###
