apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpl-backend
  labels:
    app: fpl-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fpl-backend
  template:
    metadata:
      name: fpl-backend
      labels:
        app: fpl-backend
    spec:
      containers:
        - name: fpl-backend
          image: bimalpaudel/fpl-exp:latest
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-service:5432/fpl_db
            - name: REDIS_URL
              value: redis://redis-service:6379/0
            - name: ALCHEMY_DB_URL
              value: postgresql+psycopg://postgres:postgres@postgres-service:5432/fpl_db
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
