apiVersion: v1
kind: Service
metadata:
  name: fpl-service
spec:
  selector:
    app: fpl-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort
  