name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fpl-exp:latest
      - 
        name: Write kubeconfig to temporary file
        run: echo "${{ secrets.KUBECONFIG_SECRET }}" > /tmp/kubeconfig
      -
        name: K8s deployments
        run: kubectl --kubeconfig=/tmp/kubeconfig apply -f ./k8s/deployments/
      -
        name: K8s services
        run: kubectl --kubeconfig=/tmp/kubeconfig apply -f ./k8s/services/
      -
        name: Clean up temporary kubeconfig file
        run: rm /tmp/kubeconfig
